### ISSUE TITLE
Composer Doesn't Load

### ISSUE THREAD

**Issue by ideerge** [leafsphp/leaf#15]
v1.5.0

> Fatal error: Uncaught Error: Class 'Leaf\Core\Leaf' not found in /var/www/html/portal/index.php:58 Stack trace: #0 {main} thrown in /var/www/html/portal/index.php on line 58

`$leaf = new Leaf\Core\Leaf;`

All other composer packages in vendors are working fine.

**Comment by mr-phlames** [comment]
What version of leaf are you currently using?
Have you tried to reinstall leaf in your project directory?

**Comment by FCardeira** [comment]
I know this is already closed but I have the same problem. I have version 1.3.

**Comment by ideerge** [comment]
I already wrote the info above, 1.5. I tried everything, never worked, i think i tried different version as well. this is run on EC2 amazon linux

**Comment by mr-phlames** [comment]
This happens only when hosted?

**Comment by mr-phlames** [comment]
Or do you experience this problem on localhost as well?

**Comment by FCardeira** [comment]
> Or do you experience this problem on localhost as well?

I’m experiencing this in localhost...

**Comment by mr-phlames** [comment]
Can you pls hold on, a fix will be made available in a couple of minutes🙏

**Comment by mr-phlames** [comment]
Pls try using this for your installation instead
```bash
composer require leafs/leaf ^v1.x-dev
```

**Comment by FCardeira** [comment]
I get this error from composer:

`[InvalidArgumentException]                                         
  Could not find package leafs/leaf in a version matching ^v1.x-dev `

**Comment by FCardeira** [comment]
> Pls try using this for your installation instead
> 
> ```shell
> composer require leafs/leaf ^v1.x-dev
> ```

It worked, thank you!

**Comment by mr-phlames** [comment]
Glad I could help😎
