### ISSUE TITLE
Multiple instances?

### ISSUE THREAD

**Issue by aolko** [leafsphp/leaf#2]
Can i have multiple instance of leaf in different dirs?
```
/
L api/ <- leaf instance 1
  L v1/
  L v2/
L admin-api/ <- leaf instance 2
  L v1/
```

**Comment by mr-phlames** [comment]
Thanks for reaching out, yes you can have multiple instances of Leaf in different directories

**Comment by mr-phlames** [comment]
/
L api/ <- leaf instance 1
  L v1/
  L v2/
L admin-api/ <- leaf instance 2
  L v1/


The instances are treated as separate projects, if there's no link between them...no shared variables...
If you want them to be recognised as the same project, you can create a single file and initialise leaf there....then you require the adminAPI and the userAPI files like this

```bash
/
L index.php
L api/ <- leaf instance 1
  L v1/
  L v2/
L admin-api/ <- leaf instance 2
  L v1/
```

_index.php_
```php
use Leaf\Core\Leaf;
$leaf = new Leaf();

require __DIR__. "/api/v1/..";
require __DIR__. "/api/v2/..";
require __DIR__. "/admin-api/v1/..";
```
