### ISSUE TITLE
Docs for templating Not found

### ISSUE THREAD

**Issue by vizarch** [leafsphp/leaf#20]
Why https://leafphp.netlify.app/#/2.0/templating/ don't work?

URL is here: https://leafphp.netlify.app/#/2.0/http/response?id=renderpage

**Comment by mr-phlames** [comment]
Hello Vizarch, sorry about your issue, I'd like to know where you found the first link so I can correct it.

Leaf 2.0 has default support for vein and blade templates. You can find those docs at https://leafphp.netlify.app/#/2.0/views/veins and https://leafphp.netlify.app/#/2.0/views/blade

The second link you gave is not for templating, but for outputting html with correct headers.

Hope this solves your problem, happy coding.
