### ISSUE TITLE
Db choose undefined on version 2.1.0

### ISSUE THREAD

**Issue by cubeweb** [leafsphp/leaf#26]
I am getting PHP Fatal error:  Uncaught Error: Call to undefined method Leaf\Db::choose() after updating to 2.1.0 using

```
$leaf = new Leaf\App();
$leaf->db->connect($dbHost, $dbUser, $dbPassword, $dbDatabase);
```

I had to do this to fix it

```
$leaf = new Leaf\App();
$db = new Db\Mysqli();
$leaf->db = $db;
$leaf->db->connect($dbHost, $dbUser, $dbPassword, $dbDatabase);
```

**Comment by mr-phlames** [comment]
Hello, sorry about your issue.
This error happened because the default query builder `$leaf->db` has been switched from `Leaf\Db\Mysqli` to `Leaf\Db`.

You would now have to use
```php
$db = new Leaf\Db\Mysqli;
$db->choose(...);
```

Checkout [the docs](https://leafphp.netlify.app/#/2.1/) for more info, happy coding

**Comment by cubeweb** [comment]
Thank you
