### ISSUE TITLE
Leaf Request error when sending json object as data

### ISSUE THREAD

**Issue by chatelain** [leafsphp/leaf#27]
It seems that Leaf Request doesn't handle json object as data.
For example, with this payload:
`{
    name: toto
    age: 20
    address: {
        name: 'my road'
        number: 18
        town: 'Paris'
    }
}`

I get this fatal error:
Uncaught ErrorException: htmlspecialchars() expects parameter 1 to be string, array given in C:\wamp64\www\api.mecadrive\Leaf\Http\Request.php on line 242

Is there any way to access these values with someting like:
`$request->get('address')->get('town'); // Paris`
or
```
$request->get('address');
$request['town']; // Paris
```

Thank's for the job !

**Comment by chatelain** [comment]
For the moment, i have added the following method in Request.php:
```
private function sanitize($val) {
        if (is_array($val)) {
            return array_map(array($this, 'sanitize'), $val);
        } else {
            return htmlspecialchars($val, ENT_QUOTES, 'UTF-8');
        }
    }
```

And then replaced the htmlspecialchar return with this method

**Comment by mr-phlames** [comment]
Hey chatelain, thanks for your comment, this whole issue is caused by the fact that leaf wraps all request data in the htmlspecialchars method without catering for the possibility of arrays.

Just as you've done, a fix will be made available soon. Thanks again for your comment 😇🙏

**Comment by chatelain** [comment]
Thanks for your reply.
I have modified my sanitize method to return null values because htmlspecialchars returns en empty string in case of null parameter
This is what I get:
```
private function sanitize($val) {
        if (is_array($val)) {
            return array_map(array($this, 'sanitize'), $val);
        } else {
            return is_null($val) ? null : htmlspecialchars($val, ENT_QUOTES, 'UTF-8');
        }
    }
```

**Comment by mr-phlames** [comment]
This looks good, after making sure it works in various scenarios, you can open a pull request 😇

**Comment by mr-phlames** [comment]
As promised, a temporary fix was created for this.
You can install it with  `composer require leafs\leaf v2.0.x`
