### ISSUE TITLE
Method to set charset in MySQLi

### ISSUE THREAD

**Issue by chatelain** [leafsphp/leaf#28]
I have added the following method to accept accents in file Mysqli.php
```
/**
 * Set the charset to use
 * 
 * @param string $charset: Charset
 */
public function charset(String $charset = 'utf8') {
	$this->connection->set_charset($charset);
}
```

Sorry, don't know how to pull request at the moment

**Comment by mr-phlames** [comment]
- Just fork this repo
- create a new branch with a name describing what you're doing eg: feature/add-mysqli-charset
- make the changes you want to make
- commit and push to be branch
- compare and pull request from your fork
